title:              Akmal Azizi’s Digital Marketing Blog
email:              aziziakmal31@email.com
description:        SEO, Content Strategy & Digital Marketing Insights
author:             Akmal Azizi
baseurl:            ""
url:                "https://akmalazizi.github.io"

# Social Profiles
twitter_username:   aziziakml
github_username:    akmalazizi
facebook_username:  Akm
instagram_username:  akmmmalzz
linkedin_username: in/akmal-azizi-51ba08197

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
